### PR TITLE
Recreated icons for retina displays

### PR DESCRIPTION
**Pull request by chrisssycollins**
- Recreated all of the icons, added some more (also merged and removed some)
- Added creation of all supported filetypes in the `Dockerfile`

I will open source the icons as a personal project at some point. 

Regarding #101 I would be happy to keep the project alive.

I'd like to:
- Use semantic versioning
- Use releases 
- Have a static demo site hosted at GitHub pages
- Refresh the styling slighting
- Refactor CSS

Also maybe:
- Create an open [organisation](https://github.com/organizations/new) (shared ownership)
- Have themes/icon packs hosted within the organisation

## Screenshot

screencapture-localhost-8080-1515174645693

### CODE REVIEW

**Comment by jordanbancino** [comment]
Very nice. I would love to see this merged.

**Comment by oupala** [comment]
Please update your pull request so that you try to merge to `develop` branch.

And fix the conflict.

Thanks.

**Comment by jordanbancino** [comment]
From what I can tell, you don't have an icon for `.conf` files. The default icon in apache does not follow the theme of apaxy. Is this something we can add? See #111. I have an idea for an icon, but it's not what I would consider a quality icon.

**Comment by chrisssycollins** [comment]
@oupala Conflicts fixed, also fixed the Dockerfile adding support for `{FOLDERNAME}`.

@jordanbancino `.conf` icon has been added. 

Any chance I can be added as contributor to the project so I can create branches within the repo?

**Comment by jordanbancino** [comment]
Nice. I’ll close #111

**Comment by oupala** [comment]
Good news @chrisssycollins.

Is it possible for you to rebase your commits in order to follow [conventional changelog](/conventional-changelog/conventional-changelog) convention for your commit messages? It allows to generate an automatic changelog file.

Please use [angular convention](/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

Besides, I think it is best to not mix commits from different features in a same pull request (ie. new icons vs Dockerfile fix.

For sure I will add some contributor to the projet once pull requests and issues have been purged from pending ones.

**Comment by oupala** [comment]
Hi @chrisssycollins,

Your pull request has been opened for a long time now. It is mainly my fault and I'm sorry for that.

I had a look at your pull request and I find your icons very beautiful. I think it must have taken a lot of time for you to draw all of them. I'd be pleased to merge them.

Your pull request is however a huge pull request and most of its content is already existing of fixed (or not applicable any more) in the develop branch.

Would you mind update your pull request or create a new one only to update the icons? There might be some new icons to draw for you.

For all other points of your pull request, we can discuss it here.

Please let me know what you think about all that!

**Comment by chrisssycollins** [comment]
@oupala No problem, I'll create a pull request specifically for the icons.

**Comment by oupala** [comment]
Great!

I close this pull request then.

**Pull request closed without merging**
