### PR TITLE
Added custom error pages

### PR DESCRIPTION
**Pull request by jordanbancino**
I added custom error pages that follow the style of Apaxy. Please note that when setting up, the references to the stylesheets and images will have to be updated, because they are set to `/{FOLDERNAME}/errors/` by default. These error pages are fully functional, as Apache will automatically redirect to them upon each error code. These are the common ones, I can add more if we want. See #98 

Here is an example (404 page):
example

The message will also fade down on load, just like the Apaxy website.

### CODE REVIEW

**Comment by oupala** [comment]
Could you please follow [conventional changelog](/conventional-changelog/conventional-changelog) convention for your commit messages? It allows to generate an automatic changelog file.

Please use [angular convention](/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

**Comment by oupala** [comment]
I can see that you're using specific css. I think it would be better to reuse existing css (you can complete it if you want).

You also created a new directory for `error` while these pages are part of the theme: they should be inside the teme directory.

And finally, if they reuse the existing css, there's no nedd for a specific directory, just put the error files into the `theme` directory.

Last suggestion: could it be possible to reuse `header.html` and `footer.html`?

Reusing css, header and footer will make error pages easier to maintain.

**Comment by jordanbancino** [comment]
Ok. Are you saying you want the error message to be displayed within the header and footer?

    [header]
    [error message]
    [footer]


I will move the files into the `/theme` directory and also use the existing `style.css` in the `/theme` directory, I'll just add some stuff to it.

**Comment by oupala** [comment]
Having a deeper look, I don't think any more that you should include header and footer.

Do not hesitate to amend your previous commit in order to follow conventional changelog. It'll facilitate the changelog generation.

**Comment by jordanbancino** [comment]
Ok. Sounds good. I'll take a look at the conventional changelog thing.

**Comment by jordanbancino** [comment]
@oupala I moved the error pages to the `theme` folder, and merged the required CSS into `theme/style.css`. The error pages also reference this now.

**Comment by jordanbancino** [comment]
@oupala I believe I have now completed this pull request. I will wait for your review.

**Comment by oupala** [comment]
Great.

Is it possible for you to rewite history of your commits? To squash similar commits together, to rewrite some of the first commit's message?

You'll have to use interactive rebase (git rebase -i <hash>). Is it possible for you, or not?

**Comment by jordanbancino** [comment]
I don't think  my `git rebase` worked because I had already pushed the previous commits to Github. What should I do?

**Comment by oupala** [comment]
Force push with adding `--force` flag to your `git push` command.

**Comment by jordanbancino** [comment]
Well, now `git` on my desktop only registers that I made 2 commits after performing the `rebase`, but as we can see, all 8 of my commits show on Github. I think I messed it up.

**Comment by oupala** [comment]
Have you pushed to GitHub ?

`git push --force` (`--force` is because rebasing does rewrite the history)

**Comment by jordanbancino** [comment]
Yes I did. 

    > git push --force
    Everything is up-to-date

**Comment by jordanbancino** [comment]
Should I just start over? I didn't make a whole lot of changes, It wouldn't be that hard. I'll keep in mind all the things I learned from this disaster of a pull request...

**Pull request closed without merging**
