### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Using Google's zopflipng to compress the png images losslessly, this one has better result than #49.

```
 apaxy/theme/icons/archive.png           | Bin 551 -> 403 bytes
 apaxy/theme/icons/audio.png             | Bin 554 -> 436 bytes
 apaxy/theme/icons/authors.png           | Bin 492 -> 359 bytes
 apaxy/theme/icons/bin.png               | Bin 551 -> 427 bytes
 apaxy/theme/icons/blank.png             | Bin 227 -> 96 bytes
 apaxy/theme/icons/bmp.png               | Bin 663 -> 570 bytes
 apaxy/theme/icons/c.png                 | Bin 554 -> 438 bytes
 apaxy/theme/icons/calc.png              | Bin 506 -> 405 bytes
 apaxy/theme/icons/cd.png                | Bin 757 -> 658 bytes
 apaxy/theme/icons/copying.png           | Bin 699 -> 499 bytes
 apaxy/theme/icons/cpp.png               | Bin 599 -> 469 bytes
 apaxy/theme/icons/css.png               | Bin 592 -> 467 bytes
 apaxy/theme/icons/deb.png               | Bin 671 -> 518 bytes
 apaxy/theme/icons/default.png           | Bin 311 -> 222 bytes
 apaxy/theme/icons/diff.png              | Bin 586 -> 392 bytes
 apaxy/theme/icons/doc.png               | Bin 535 -> 422 bytes
 apaxy/theme/icons/draw.png              | Bin 679 -> 546 bytes
 apaxy/theme/icons/eps.png               | Bin 619 -> 490 bytes
 apaxy/theme/icons/exe.png               | Bin 846 -> 615 bytes
 apaxy/theme/icons/folder-home.png       | Bin 618 -> 469 bytes
 apaxy/theme/icons/folder-open.png       | Bin 431 -> 324 bytes
 apaxy/theme/icons/folder-page.png       | Bin 591 -> 476 bytes
 apaxy/theme/icons/folder-parent-old.png | Bin 494 -> 311 bytes
 apaxy/theme/icons/folder-parent.png     | Bin 621 -> 444 bytes
 apaxy/theme/icons/folder.png            | Bin 395 -> 302 bytes
 apaxy/theme/icons/gif.png               | Bin 655 -> 563 bytes
 apaxy/theme/icons/gzip.png              | Bin 551 -> 403 bytes
 apaxy/theme/icons/h.png                 | Bin 504 -> 388 bytes
 apaxy/theme/icons/hpp.png               | Bin 530 -> 412 bytes
 apaxy/theme/icons/html.png              | Bin 770 -> 636 bytes
 apaxy/theme/icons/ico.png               | Bin 792 -> 665 bytes
 apaxy/theme/icons/image.png             | Bin 671 -> 578 bytes
 apaxy/theme/icons/install.png           | Bin 788 -> 585 bytes
 apaxy/theme/icons/java.png              | Bin 658 -> 551 bytes
 apaxy/theme/icons/jpg.png               | Bin 675 -> 580 bytes
 apaxy/theme/icons/js.png                | Bin 540 -> 429 bytes
 apaxy/theme/icons/json.png              | Bin 540 -> 429 bytes
 apaxy/theme/icons/log.png               | Bin 423 -> 297 bytes
 apaxy/theme/icons/makefile.png          | Bin 614 -> 437 bytes
 apaxy/theme/icons/markdown.png          | Bin 627 -> 428 bytes
 apaxy/theme/icons/package.png           | Bin 614 -> 485 bytes
 apaxy/theme/icons/pdf.png               | Bin 799 -> 666 bytes
 apaxy/theme/icons/php.png               | Bin 757 -> 578 bytes
 apaxy/theme/icons/playlist.png          | Bin 610 -> 497 bytes
 apaxy/theme/icons/png.png               | Bin 679 -> 592 bytes
 apaxy/theme/icons/pres.png              | Bin 629 -> 525 bytes
 apaxy/theme/icons/ps.png                | Bin 817 -> 694 bytes
 apaxy/theme/icons/psd.png               | Bin 622 -> 502 bytes
 apaxy/theme/icons/py.png                | Bin 743 -> 641 bytes
 apaxy/theme/icons/rar.png               | Bin 621 -> 456 bytes
 apaxy/theme/icons/rb.png                | Bin 781 -> 675 bytes
 apaxy/theme/icons/readme.png            | Bin 384 -> 265 bytes
 apaxy/theme/icons/rpm.png               | Bin 660 -> 492 bytes
 apaxy/theme/icons/rss.png               | Bin 660 -> 546 bytes
 apaxy/theme/icons/rtf.png               | Bin 627 -> 428 bytes
 apaxy/theme/icons/script.png            | Bin 613 -> 501 bytes
 apaxy/theme/icons/source.png            | Bin 586 -> 392 bytes
 apaxy/theme/icons/sql.png               | Bin 510 -> 367 bytes
 apaxy/theme/icons/tar.png               | Bin 406 -> 285 bytes
 apaxy/theme/icons/tex.png               | Bin 677 -> 542 bytes
 apaxy/theme/icons/text.png              | Bin 463 -> 345 bytes
 apaxy/theme/icons/tiff.png              | Bin 654 -> 558 bytes
 apaxy/theme/icons/unknown.png           | Bin 556 -> 418 bytes
 apaxy/theme/icons/vcal.png              | Bin 556 -> 383 bytes
 apaxy/theme/icons/video.png             | Bin 739 -> 581 bytes
 apaxy/theme/icons/xml.png               | Bin 585 -> 443 bytes
 apaxy/theme/icons/zip.png               | Bin 617 -> 453 bytes
```

### CODE REVIEW

**Comment by nodiscc** [comment]
It would also be worth testing with `pngcrush` and `optipng`  and compare the results.

**Comment by PeterDaveHello** [comment]
@nodiscc by my experience, zopflipng usually has better result than optipng.

**Comment by nodiscc** [comment]
```
31449	zopfli
41857	optipng
41848	pngcrush
44541	unoptimized
```

:+1:

**Comment by nodiscc** [comment]
@AdamWhitcroft Can this be merged?

**Comment by nodiscc** [comment]
It would be worth comparing against PNGs compressed with https://github.com/Kilian/Trimage, for completeness sake

**Comment by oupala** [comment]
This branch is old.

apaxy has been transferred to a new team and we're trying to do the housework between all pending issues and pull requests.

We decided to close this pull request. Please reclaim if you want this pull request to be re-opened, discussed and reviewed again.

**Comment by PeterDaveHello** [comment]
@oupala yes please, I can update the branch.

**Comment by oupala** [comment]
In fact, we plan to replace all icons by other icons (see #86, #103). As a consequence, there no real need to optimize existing images.

That's why we wanted to close this pull request.

@chrisssycollins could pay attention to optimize image of your new set of icons?

**Comment by chrisssycollins** [comment]
@oupala I'll make sure they are fully optimised.

**Pull request closed without merging**
