### PR TITLE
Allow icon also for PDF

### PR DESCRIPTION
**Pull request by pcav**

### CODE REVIEW

**Comment by jordanbancino** [comment]
Oh, I didn't know apache was case sensitive. In this case, should we do that for all the file extensions? Or at least some additional common ones like `.ISO` and `.PNG`?

**Comment by pcav** [comment]
Agreed, it would be good to replicate it for all. I didn't do it because I did not know whather this was acceptable for you, or if there is a better solution. Possibly also .Pdf etc could be added.
Thanks.

**Comment by oupala** [comment]
I'm not a big fan of duplicating extension. It is against the DRY principle (Don't Repeat Yourself).

Lowercase extension is not enough?

There is some tools to batch-rename files.

What do you think?

**Comment by pcav** [comment]
It makes sense to me. On the other hand, it might be disturbing to the user, especially if there are frequent new uploads to the folder.
Decision is yours :)

**Comment by oupala** [comment]
Decision is not mine, I'm not omnipotent.

We will close this issue, for sure as it only concernes `pdf` extension.

But it is a good place to discuss about duplicating **all** `.ext` to `.EXT` or **none**.

Go and give your opinion!

**Comment by pcav** [comment]
Thanks. As said, I have no strong opinion (otherwise I'd have defended it as usual ;) ).

**Comment by oupala** [comment]
Thanks for you (not strong) opinion.

I would also like to have the opinion of other users.

**Comment by jordanbancino** [comment]
Yeah, I’d say it’s too repetitive. The `.htaccess` file would get very messy very quickly, making it difficult to maintain.

**Comment by danielwinther** [comment]
Definitely too repetitive. I tend to use a server command for that kind of grunt work - such as `rename 's/\.PDF$/\.pdf/' *.PDF` to rename all extensions with .PDF to .pdf in a specific directory.

**Comment by jordanbancino** [comment]
Ok. Then should we close this @oupala ? Maybe we could add something to the README about this?

**Comment by oupala** [comment]
I was looking at apache documentation, and I think that we could maybe try to use `AddIconByType` instead of `AddIcon`.

[AddIconByType](https://httpd.apache.org/docs/2.4/en/mod/mod_autoindex.html#addiconbytype) might be the solution as `file.pdf` and `FILE.PDF` should have the same mime type.

Hence this could solve the issue, choosing the icon depending on the mime type instead of the file extension.

**Comment by pcav** [comment]
It seems the way to go.
Thanks.

**Comment by oupala** [comment]
Can you test it and tell us if it works?

If it does, we might change all the `AddIcon` to `AddIconByType`.

**Comment by pcav** [comment]
Will do ASAP

**Comment by pcav** [comment]
I confirm,
`	AddIconByType (PDF,theme/icons/pdf.png) *`
works.

**Comment by oupala** [comment]
Ok, I will close this pull request and start a new one trying to replace all the `AddIcon` directive to `AddIconByType`.

**Pull request closed without merging**
