### PR TITLE
feat: Add styled error pages

### LINKED ISSUE #98: Custom Error Pages
It would be great to have custom HTTP error pages to go with the theme. Will look into this myself.

### PR DESCRIPTION
**Pull request by jordanbancino**
I added custom error pages that follow the style of Apaxy. These error pages are fully functional, as Apache will automatically redirect to them upon each error code. These are the common ones, I can add more if we want. This closes #98

Here are the errors I implemented:
- 400
- 403
- 404
- 408
- 500
- 502

Here is an example (404 page):

example

The message will also fade down on load, just like the Apaxy website. We can always add more errors if we want.

### CODE REVIEW

**Comment by oupala** [comment]
Your pull request is trying to merge to `master`. Can you update it to merge to `develop`?

And can you please pay attention to the style refactoring made by @PeterDaveHello in pull request #108. Thanks.

**Comment by oupala** [comment]
And do not forget to mention that your commit closes issue #98 by adding the following to your commit message:

```
close #98
```

as I did on this commit: 4471ec1b9f0b966738c4dab8cd423b871b951a5b (more information here [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/), I personally prefer `close` keyword).

**Comment by jordanbancino** [comment]
Ok. I will merge branch `develop` into `jordanbancino/patch-1` and set `jordanbancino/patch-1` to merge into `develop`. I will also add `close #98` to the commit message.

**Comment by jordanbancino** [comment]
I reviewed the article you referenced, and I used the `closes` keyword in the pull request description, so if this gets merged, it will close it automatically, without me needing to put it in a commit message.

**Comment by danielwinther** [comment]
Just a mere suggestion; wouldn't it be better to reuse the HTML error pages? The only thing that changes in the HTML is the error code and error message depending on which error is triggered. Instead of having 6 (or more) almost identical HTML files - we could have just a single one.

This would make it easier to:
- Change the overall layout for **all** errors at once - otherwise you'd have to change the HTML in all the files individually.
- Naturally make the theme smaller in terms of storage on the hard drive. Less files = less space.
- Adding a new error page is more manageable.

I'm thinking something along these lines;
```
ErrorDocument 400 http://%{HTTP_HOST}/{FOLDERNAME}/theme/error.html?code=400
ErrorDocument 403 http://%{HTTP_HOST}/{FOLDERNAME}/theme/error.html?code=403
ErrorDocument 404 http://%{HTTP_HOST}/{FOLDERNAME}/theme/error.html?code=404
ErrorDocument 408 http://%{HTTP_HOST}/{FOLDERNAME}/theme/error.html?code=408
ErrorDocument 500 http://%{HTTP_HOST}/{FOLDERNAME}/theme/error.html?code=500
ErrorDocument 502 http://%{HTTP_HOST}/{FOLDERNAME}/theme/error.html?code=502
```
The error code is sent as parameter in a query string - which is then parsed in a switch case statement with JavaScript/jQuery and then displays the appropriate error message depending on the parameter that was sent.

Any input on this? :)

**Comment by oupala** [comment]
I like to have an easy static solution that does not require any js processing on the client side.

I think it was a good idea to merge the current pull request as is.

It should not prevent you to test your idea in another pull request, so that we can compare the two solutions.

**Comment by nodiscc** [comment]
> error code is sent as parameter in a query string - which is then parsed in a switch case statement with JavaScript/jQuery

Please try to avoid unneeded dependencies :/ I like the fact that Apaxy is simple and makes use of standard apache features. If you are looking for something more complex, have a look at https://larsjung.de/h5ai/

**Comment by oupala** [comment]
I agree with @nodiscc.

But I think there is a huge difference between h5ai and apaxy: while h5ai needs php and some server side processing in php, apaxy will stay an apache + client side solution.

If we add an external dependencie, it will be manager by the automation script (see #107) while the standard version of apaxy will remain simple and self-contained.

**Pull request merged**
