### PR TITLE
[DOC] Fix table of content links and improves titles style

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
New separated PR for some README fixes/improvements.

### CODE REVIEW

**Comment by oupala** [comment]
I don't see the point of this pull request which is mainly a revert of a [previous commit](https://github.com/oupala/apaxy/commit/412d45f564357cedbb53640ad9b6f5d330db4e21#diff-04c6e90faac2675aa89e2176d2eec7d8).

Could you explain me why you prefer capitalized titles?

**Comment by HorlogeSkynet** [comment]
Oh I didn't mean to enforce a special way of presenting this.
I had just encountered some broken links, and by fixing them, I've taken the opportunity to improve consistency between titles casing (and in our language, titles have to be capitalized so it appeared logical ¯\_ (ツ) _/¯).

**Comment by oupala** [comment]
Oh I see, I did not see the broken links, thanks!

Can you give me a reference that explains how and why capitalize title? To me, it make titles hard to read.

**Comment by HorlogeSkynet** [comment]
No problem, here you go : <https://www.proz.com/kudoz/English/computers-systems-networks/5001694-capitalization-in-table-of-contents.html>

**Comment by oupala** [comment]
I think fixing the broken links is important.

But I'm not sure to change the titles' capitalization, as it lower the titles' readability.

**Comment by HorlogeSkynet** [comment]
As you want !
You got write access on the corresponding branch to edit changes as you wish.
Don't you have any "collaborator" among the community to emit thoughts about such modifications ?

Bye 👋

**Comment by oupala** [comment]
The toc has been fixed in another commit.

**Comment by HorlogeSkynet** [comment]
:+1:
What I meant is : For "big" projects, maintainers tend to grant write access (or at least give a reviewing voice) to some known contributors so as to share responsibilities and sometimes help in "difficult" choices.

**Comment by oupala** [comment]
I don't think apaxy is a big project, it is only a small addition to apache httpd server.

Apaxy has been initiated and created by @AdamWhitcroft and he has been maintaining it for years. He then decided to retire and choosed to let me be the admin of the project. This is quite recent and I mainly tried to fix the alreadt existing issues and pull request to have a strong and up to date basis on which we can propose some new features. Here we are now.

I'll have to think about what to do now, if I need some helpers on this project, what feature should be added. But for the moment, we're still on the thinking phase.

**Pull request closed without merging**
