### PR TITLE
refactor: replace some AddIcon directives by AddIconByType

### PR DESCRIPTION
**Pull request by oupala**
I started to replace some AddIcon directives by AddIconByType.

It seems to work and is a good oppotunity to simplify the `.htaccess` file.

This work needs to find all used mime-types.

### CODE REVIEW

**Comment by jordanbancino** [comment]
Oh if this works, then this is great! It is a much better idea to assign icons based on file type, rather than file extension.

**Comment by oupala** [comment]
There are many advantages of using mime type instead of using file extension:

- it is shorter to write:

> The generic mime type `video/*` is way shorter than a long list of extensions `.asf .asx .avi .flv .mkv .mov .mp4 .mpg .rm .srt .swf .vob .wmv .m4v .f4v .f4p .ogv`.

- it handles all mime sub-types, including futur mime types for futur video formats
- it is more reliable

> Imagine an *mp4 video* file uncorrectly renamed to `myvideo.mp3`, it should be displayed as a video, not as an *mp3 audio*, as **it is** a video.

**Comment by oupala** [comment]
*Mime types* are now named *media types* at [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml).

The list of media types currently supported by apache can be generated using the following oneliner:

- sorted by media types:

```bash
wget -qO- http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types | egrep -v ^# | sort
```

- sorted by file extension:

```bash
wget -qO- http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types | egrep -v ^# | awk '{ for (i=2; i<=NF; i++) {print $i" "$1}}' | sort
```

For file type without supported media type by apache, we'll have to fall back to the old way (`AddIcon` instead of `AddIconByType`).

**Comment by oupala** [comment]
I have added all useful media type in apaxy. Consequently, it should have added a lot of file extensions to apaxy supported file extension list.

It was a long research to switch from file extension to corresponding media type, then from media type to all supported file extension. But htaccess and documentation should be up to date.

**Pull request merged**
