### PR TITLE
Minor fixes to the error pages.

### LINKED ISSUE #138: The error pages do not have valid HTML.
**Describe the bug**
The error pages (e.g. `apaxy/apaxy/theme/404.html`, etc.) do not have valid HTML.

Their doctype is missing a `!` character, and they use `<center>`, which is obsolete in HTML5.

### PR DESCRIPTION
**Pull request by sheeit**
Fixes #138

### CODE REVIEW

**Comment by sheeit** [comment]
> Thanks for the report and for the merge request.
> 
> We try not to include css inside html. Can you please add the inline css into the separate css file?

Sure!

**Comment by oupala** [comment]
The code seems now ok. I have to check and test it.

Thank you.

**Comment by oupala** [comment]
Ok, the code is ok and I tested it. Nothing to say about it.

Can you please squash and rebase your commit to follow the contributing guide:

> The commit message of each commit of the merge request does not follow the conventional commits standard.

In my opinion, there should only be 2 commits in the end:

- Fix the doctype in the error pages.
- Use style="text-algin: center" instead of <center>

**Comment by sheeit** [comment]
Alright, I've done that. I had to do some reading on the git documentation, but I figured it out at the end. Cheers.

**Comment by oupala** [comment]
That's great, apaxy gained a better code, and on your part you learned something!

**Pull request merged**
