### PR TITLE
New icons and file extensions

### PR DESCRIPTION
**Pull request by oxguy3**
This PR adds supports for a ton of additional file extensions and four new icons (from the same Faenza icon set that the existing icons come from). This PR is a lot of small additions, but some of the major additions:

* New icon for presentations (i.e. PowerPoint)
* New icon for fonts
* Additional file extensions for various programming languages (Java, Python, PHP, Bash)
* Comic book archive file extensions (.cbz, .cbr, etc)
* Additional audio/video file types

### CODE REVIEW

**Comment by jordanbancino** [comment]
#103

**Comment by oupala** [comment]
Please update your pull request so that you try to merge to `develop` branch.

And fix the conflict.

Thanks.

**Comment by oupala** [comment]
@oxguy3 I'll be pleased to merge your pull request, if there was no conflicts.

Could you please update your pull request so that you try to merge to `develop` branch? Thanks.

**Comment by oupala** [comment]
Your pull request is quite old (mainly my fault) and most of its content is already in the branch *feature/mimetypes*. Can you please check it to see if you wan to add anything?

I've added 3 of the four icons (I did not add the flash icon as I believe it is not useful anymore, as flash has disappeared from the web).

I have also changed the way file support is added (media type instead of file extension). That's why I think the content of your pull request cannot be merged now. Hence I will close it.

Thanks for contributing and do not hesitate to answer here or in the [*feature/mimetypes* pull request](#116).

**Pull request closed without merging**
