### PR TITLE
Give .crx Files a Chrome Icon

### PR DESCRIPTION
**Pull request by KennyStier61**
Add a Google Chrome icon (from Faenza) and give Google Chrome packaged extensions (.crx) a Google Chrome icon.

### CODE REVIEW

**Comment by oupala** [comment]
Could you please follow [conventional changelog](/conventional-changelog/conventional-changelog) convention for your commit messages? It allows to generate an automatic changelog file.

Please use [angular convention](/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

**Comment by oupala** [comment]
Why have you added `.iso` extension to README file?

**Comment by jordanbancino** [comment]
Looks good! 👍

**Comment by oupala** [comment]
Please update your pull request so that you try to merge to `develop` branch.

And add only `crx` extension, not `iso`.

Thanks.

**Comment by chrisssycollins** [comment]
@oupala @KennyStier61 I've added `.crx` into #103.

**Comment by oupala** [comment]
Closing this pull request as is it handled by #103.

**Pull request closed without merging**
