### PR TITLE
Improve code readability, maintainability, style

### PR DESCRIPTION
**Pull request by PeterDaveHello**
The origin files have some trailing space, trailing newline, indentation issues, AKA coding style issues, this pull request can help improve the readability and more important the maintainability of codes in this project.

I could help integrate some checking with continuous integration to help test future changes to prevent regression issues.

### CODE REVIEW

**Comment by oupala** [comment]
This looks good.

Could you please follow [conventional changelog](/conventional-changelog/conventional-changelog) convention for your commit messages? It allows to generate an automatic changelog file.

Please use [angular convention](/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular).

**Comment by PeterDaveHello** [comment]
Should be good now?

**Comment by oupala** [comment]
Commit message is good, but you're pull request is trying to merge into master while the development branch is `develop`.

**Comment by PeterDaveHello** [comment]
So, maybe the default branch should be `develop` not `master`? Can we have contribution guide about these rules?

**Comment by oupala** [comment]
You're right, I just changed the default branch from `master` to `develop`.

**Comment by PeterDaveHello** [comment]
Done.

**Comment by oupala** [comment]
By the way, do you want to start a new contribution guide?

**Comment by PeterDaveHello** [comment]
If I'm one of the collaborators in this project, yes, of course.

**Pull request merged**
