### PR TITLE
Fix: Add missing comma at the end of lines 2 and 3 of /apaxy/theme/apaxy-lightgallery.js

### LINKED ISSUE #160: Syntax error in /apaxy/theme/apaxy-lightgallery.js
**Describe the bug**
Lines 2 and 3 in the file `/apaxy/theme/apaxy-lightgallery.js` are missing a comma. This causes a syntax error, so lightgallery does not work when enabled. 

**To Reproduce**
1. Install Apaxy with lightgallery
2. Open an image in an indexed directory on the web server
3. The image opens directly instead of using lightgallery

**Expected behavior**
The image should have opened in lightgallery. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 131

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 14
 - Browser Firefox
 - Version 131

**Additional context**
Adding the 2 missing commas fixes the issue.

### PR DESCRIPTION
**Pull request by TechnologyMan101**
fixes #160 

## proposed changes

- Add comma at the end of line 2
- Add comma at the end of line 3

### CODE REVIEW

**Comment by oupala** [comment]
You're right @TechnologyMan101, the previous merge request instroduced a syntax error.

Can you please rebase your merge request on the `2.5.0` tag (commit `e95b162`) as this will be a patch release?

**Comment by TechnologyMan101** [comment]
Oops looks like I may have messed something up here

**Comment by TechnologyMan101** [comment]
I've put it back to the original base for now since rebasing also pulled the changed package.json. 

If you don't mind me asking, what would be the correct way to rebase this pull request, considering I did this PR completely on the web browser?

**Comment by oupala** [comment]
Thanks for your contribution.

I did what I need in the merge request.

**Pull request merged**
